configs.services:
  type: py
  files:
    - app
    - cache
    - logger
    - rcl
    - subprocesses
    - db
    - printing
    - ocr_convertor
    - scan
    #: BUILD_TYPE:server
    - server
    #: END:BUILD_TYPE:server
    #: BUILD_TYPE:!server
    - client
    #: END:BUILD_TYPE:!server
    #: BUILD_TYPE:client-ui
    - notifications
    - langs
    - ui
    #: END:BUILD_TYPE:client-ui

#: BUILD_TYPE:client-ui
configs.ui:
  type: json
  files:
    - menu
    - shortcuts
#: END:BUILD_TYPE:client-ui